import type { PresetName, Theme } from '../types/theme';

const base: Omit<Theme, 'background' | 'fog' | 'piano' | 'bars' | 'particles' | 'postfx'> & {
  camera: Theme['camera'];
} = {
  version: 1,
  camera: { tiltDeg: 40, distance: 12, offsetYFrac: 0.35 },
};

export const PRESETS: Record<PresetName, Theme> = {
  default: {
    ...base,
    background: '#05060a',
    fog: { color: '#05060a', near: 18, far: 40 },
    piano: {
      whiteBase: '#f5f5f5',
      blackBase: '#111111',
      pressGlow: '#00f5a0',
      pressEmissiveIntensity: 1.4,
      pressDepth: 0.05,
    },
    bars: {
      colorTop: '#00f5a0',
      colorBottom: '#00b4d8',
      emissiveColor: '#00f5a0',
      emissiveIntensity: 0.6,
      roughness: 0.3,
      metalness: 0.15,
    },
    particles: {
      enabled: true,
      color: '#00f5a0',
      burstCount: 10,
      poolSize: 1024,
      gravityY: -2.4,
      lifeMin: 0.7,
      lifeMax: 1.2,
      initialVelY: 1.8,
      spread: 0.3,
      size: 22,
    },
    postfx: {
      bloomIntensity: 0.9,
      bloomThreshold: 0.45,
      bloomRadius: 0.75,
      chromaticOffset: 0.0006,
      vignetteDarkness: 0.6,
    },
  },
  neon: {
    ...base,
    background: '#0a0612',
    fog: { color: '#0a0612', near: 18, far: 40 },
    piano: {
      whiteBase: '#f5f5f5',
      blackBase: '#0a0a0a',
      pressGlow: '#ff2d6b',
      pressEmissiveIntensity: 1.8,
      pressDepth: 0.05,
    },
    bars: {
      colorTop: '#ff2d6b',
      colorBottom: '#7b2fff',
      emissiveColor: '#ff2d6b',
      emissiveIntensity: 1.1,
      roughness: 0.2,
      metalness: 0.25,
    },
    particles: {
      enabled: true,
      color: '#ff4d8a',
      burstCount: 14,
      poolSize: 1536,
      gravityY: -1.8,
      lifeMin: 0.8,
      lifeMax: 1.4,
      initialVelY: 2.2,
      spread: 0.35,
      size: 26,
    },
    postfx: {
      bloomIntensity: 1.3,
      bloomThreshold: 0.35,
      bloomRadius: 0.85,
      chromaticOffset: 0.0012,
      vignetteDarkness: 0.7,
    },
  },
  fire: {
    ...base,
    background: '#0a0403',
    fog: { color: '#1a0800', near: 16, far: 38 },
    piano: {
      whiteBase: '#f3ece4',
      blackBase: '#1a0d06',
      pressGlow: '#ffb347',
      pressEmissiveIntensity: 2.0,
      pressDepth: 0.05,
    },
    bars: {
      colorTop: '#ffd166',
      colorBottom: '#ff5a1f',
      emissiveColor: '#ff7a1a',
      emissiveIntensity: 1.4,
      roughness: 0.45,
      metalness: 0.05,
    },
    particles: {
      enabled: true,
      color: '#ffb347',
      burstCount: 16,
      poolSize: 2048,
      gravityY: -0.6,   // embers rise slow
      lifeMin: 0.9,
      lifeMax: 1.8,
      initialVelY: 2.5,
      spread: 0.45,
      size: 24,
    },
    postfx: {
      bloomIntensity: 1.5,
      bloomThreshold: 0.35,
      bloomRadius: 0.9,
      chromaticOffset: 0.0008,
      vignetteDarkness: 0.75,
    },
  },
  water: {
    ...base,
    background: '#02060d',
    fog: { color: '#041024', near: 18, far: 42 },
    piano: {
      whiteBase: '#eaf6ff',
      blackBase: '#081422',
      pressGlow: '#66e1ff',
      pressEmissiveIntensity: 1.6,
      pressDepth: 0.05,
    },
    bars: {
      colorTop: '#b8f3ff',
      colorBottom: '#0a84ff',
      emissiveColor: '#66e1ff',
      emissiveIntensity: 0.9,
      roughness: 0.15,
      metalness: 0.5,
    },
    particles: {
      enabled: true,
      color: '#b8f3ff',
      burstCount: 12,
      poolSize: 1536,
      gravityY: -3.5,
      lifeMin: 0.6,
      lifeMax: 1.1,
      initialVelY: 2.0,
      spread: 0.5,
      size: 20,
    },
    postfx: {
      bloomIntensity: 1.0,
      bloomThreshold: 0.4,
      bloomRadius: 0.8,
      chromaticOffset: 0.0004,
      vignetteDarkness: 0.55,
    },
  },
  crystal: {
    ...base,
    background: '#070510',
    fog: { color: '#0a0820', near: 18, far: 40 },
    piano: {
      whiteBase: '#fafafa',
      blackBase: '#0c0c18',
      pressGlow: '#ffffff',
      pressEmissiveIntensity: 1.9,
      pressDepth: 0.05,
    },
    bars: {
      colorTop: '#ffffff',
      colorBottom: '#b892ff',
      emissiveColor: '#d8b8ff',
      emissiveIntensity: 1.2,
      roughness: 0.05,
      metalness: 0.8,
    },
    particles: {
      enabled: true,
      color: '#ffffff',
      burstCount: 18,
      poolSize: 2048,
      gravityY: -2.0,
      lifeMin: 0.8,
      lifeMax: 1.5,
      initialVelY: 2.4,
      spread: 0.5,
      size: 18,
    },
    postfx: {
      bloomIntensity: 1.2,
      bloomThreshold: 0.5,
      bloomRadius: 0.7,
      chromaticOffset: 0.001,
      vignetteDarkness: 0.6,
    },
  },
};

export const DEFAULT_PRESET: PresetName = 'default';
